export { default as Home } from "./Home"
export { default as Evas } from "./Evas"
export { default as EvasChooseBook } from "./EvasChooseBook"
export { default as EvasShowLectures } from "./EvasShowLectures"
export { default as EvasCart } from "./EvasCart"
export { default as Attendency } from "./Attendency"
export { default as Blog } from "./Blog"
